### ISSUE TITLE
fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by bishesh** [SimpleITK/SimpleITKCondaRecipe#20]
I have anaconda3 installed with python 3 where I created a new conda env to install simpleitk.
After editing the meta.yml to have the latest master version (version: "your_custom_version", git_tag: master), I tried to do `conda build recipe` in the conda env, but it gives the error (below). There are other packages working fine in the same env.

```
In file included from /home/bk17/anaconda3/conda-bld/simpleitk_1500393985191/work/Wrapping/Python/sitkPyCommand.cxx:22:0:
/home/bk17/anaconda3/conda-bld/simpleitk_1500393985191/work/Wrapping/Python/sitkPython.h:71:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
In file included from /home/bk17/anaconda3/conda-bld/simpleitk_1500393985191/work/build/SimpleITK-build/Wrapping/Python/SimpleITKPYTHON_wrap.cxx:11:0:
/home/bk17/anaconda3/conda-bld/simpleitk_1500393985191/work/Wrapping/Python/sitkPython.h:71:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
make[5]: *** [Wrapping/Python/CMakeFiles/SimpleITK_PYTHON.dir/sitkPyCommand.cxx.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: *** [Wrapping/Python/CMakeFiles/SimpleITK_PYTHON.dir/SimpleITKPYTHON_wrap.cxx.o] Error 1
make[4]: *** [Wrapping/Python/CMakeFiles/SimpleITK_PYTHON.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/bk17/anaconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/bk17/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/home/bk17/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/home/bk17/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 183, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/bk17/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1615, in build_tree
    built_packages=built_packages,
  File "/home/bk17/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1072, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/home/bk17/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 670, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/home/bk17/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 666, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/home/bk17/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/home/bk17/anaconda3/conda-bld/simpleitk_1500393985191/work/conda_build.sh']' returned non-zero exit status 2.
```

**Comment by zivy** [comment]
Just built on my system (OS X 10.11.6 ) and did not get the error.  My slightly old versions of conda and conda-build are: conda 4.3.13, conda-build 2.1.3 

I don't think this has to do with the env you activated as conda-build is only installed in the root environment. 

Please provide the following details so that we can try to reproduce the error:
OS and version, conda version, conda-build version, targeted python version.

**Comment by bishesh** [comment]
**OS:** Ubuntu 14.04.05 LTS
**conda:** conda 4.3.22, conda-build 3.0.6 and Anaconda 4.4.0 (64-bit)
**python:** 3.6.1

The build goes up to 100% normally and then at the final stage gives the error.

**Comment by blowekamp** [comment]
I was able to reproduce the problem with the following docker file:
```
FROM ubuntu:14.04

RUN apt-get update && \
    apt-get install -y \
    build-essential git

RUN apt-get install -y emacs

ADD https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh /tmp
WORKDIR /tmp

RUN /bin/bash Anaconda3-*-Linux-x86_64.sh -p /opt/anaconda3 -b && rm -f Anaconda3-4.4.0-Linux-x86_64.sh

RUN /opt/anaconda3/bin/conda install -n root conda-build -y
   

RUN useradd  --create-home --shell /bin/bash dockeruser

USER dockeruser

WORKDIR /home/dockeruser

RUN git clone https://github.com/SimpleITK/SimpleITKCondaRecipe.git
RUN sed -i 's/1\.0\.0/master/g' SimpleITKCondaRecipe/recipe/meta.yaml && cat SimpleITKCondaRecipe/recipe/meta.yaml

ENTRYPOINT CONDA_ROOT=/opt/anaconda3/ PYTHON_VERSIONS="36" CONDA_RECIPES=/home/dockeruser/SimpleITKCondaRecipe SimpleITKCondaRecipe/scripts/CondaBuild.sh
```
